# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Angular App Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      HOST: ssh.rosti.cz
      USER: app
      PORT: 27211
      NODE_VERSION: 21.2.0
      APP_NAME: ng-recipe-app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'v21.2.0'

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup hostkey
        run: echo "ssh.rosti.cz ssh-rsa ${{ secrets.SSH_KEY }}" > ./known_hosts

      - name: npm install
        run: npm install

      - name: build
        run: npm run build:prod

      # Copy app files to server 'public' folder
      - name: Copy public folder files
        run: |
          rsync -ae "ssh -o UserKnownHostsFile=./known_hosts -p $PORT" \
          --filter='- index.html' \
          ./dist/$APP_NAME/* $USER@$HOST:/srv/app/express/public

      - name: Apply changes
        run: |
          ssh -o UserKnownHostsFile=./known_hosts -p $PORT $USER@$HOST supervisorctl reread
          ssh -o UserKnownHostsFile=./known_hosts -p $PORT $USER@$HOST supervisorctl update
          ssh -o UserKnownHostsFile=./known_hosts -p $PORT $USER@$HOST supervisorctl restart app
          ssh -o UserKnownHostsFile=./known_hosts -p $PORT $USER@$HOST supervisorctl restart nginx
